spring:  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/customer_service
    username: root
    password: '{cipher}d6d19fa129f473cfee99ac296e72cd8e4eba1c47c0d967fde54268493d99ed16'
    driver-class-name: com.mysql.jdbc.Driver 
